### PR TITLE
Fix sun_roof_percent_open for Model3

### LINKED ISSUE #19: Error with sun_roof_percent_open
I think the models need to allow nullable types for somethings. I'm getting this querying a Model 3:

`Newtonsoft.Json: Error converting value {null} to type 'System.Int64'. Path 'response.sun_roof_percent_open', line 1, position 619. System.Private.CoreLib: Null object cannot be converted to a value type.`

### PR DESCRIPTION
**Pull request by p3root**
Fixes #19 - more or less the same change #38, but I have left all deps as they are + I added some unit tests for the changes.

### CODE REVIEW

**Comment by p3root** [comment]
This fix is very urgent to me. I hope you can check that very soon :)

**Comment by p3root** [comment]
Please don't forget to update the NuGet package :) thanks for merging.

**Comment by JSkimming** [comment]
@p3root Yeah, I'll release later today. Thanks for the contribution by the way. I merged this quickly yesterday as I was just heading out to the Cinema to watch Endgame.

**Comment by JSkimming** [comment]
@p3root I've just pushed [0.7.0 to NuGet](https://www.nuget.org/packages/Tesla.NET/0.7.0 "Tesla.NET 0.7.0"), it should be available in a few minutes

**Comment by p3root** [comment]
Merci :)

**Pull request merged**
