### PR TITLE
Fix issue with SunRoofPercentOpen, Update dependencies, fix minor StyleCop stuff

### PR DESCRIPTION
**Pull request by MichelZ**

### CODE REVIEW

**Comment by MichelZ** [comment]
Fixes #19

**Comment by JSkimming** [comment]
@MichelZ The build is breaking because of the upgrade to `coverlet.msbuild` see #33.

I'm not sure what's wrong with the latest version of `coverlet.msbuild`, I'm going to tackle it when I have more time. If you can remove that part of the upgrade, then I'll merge this in.

**Comment by p3root** [comment]
Any updates to this PR?

**Comment by JSkimming** [comment]
Superseded by #45

**Pull request closed without merging**
